# Generated by Django 2.1.5 on 2019-01-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_platform',
            new_name='platform',
        ),
    ]
